return {
	-- 	'dmtrKovalenko/fff.nvim',
	-- 	build = function()
	-- 		-- downloads a prebuilt binary or falls back to cargo build
	-- 		require("fff.download").download_or_build_binary()
	-- 	end,
	-- 	-- for nixos:
	-- 	-- build = "nix run .#release",
	-- 	opts = {
	-- 		debug = {
	-- 			enabled = true,
	-- 			show_scores = true,
	-- 		},
	-- 	},
	-- 	lazy = false, -- the plugin lazy-initialises itself
	-- 	keys = {
	-- 		-- { "<leader>sf", function() require('fff').find_files() end,                                           desc = 'FFFind files' },
	-- 		-- { "<leader>sg", function() require('fff').live_grep() end,                                            desc = 'LiFFFe grep' },
	-- 		-- { "<leader>sz", function() require('fff').live_grep({ grep = { modes = { 'fuzzy', 'plain' } } }) end, desc = 'Live fffuzy grep', },
	-- 		-- { "<leader>sw", function() require('fff').live_grep_under_cursor() end,                               mode = { 'n', 'x' },       desc = 'Search current word / selection', },
	-- 	},
	-- 	config = function()
	-- 		local fff = require('fff')
	--
	-- 		vim.keymap.set('n', "<leader>sf", function()
	-- 			fff.find_files()
	-- 		end, { desc = 'FFFind files' })
	-- 		vim.keymap.set('n', "<leader>sg", function() fff.live_grep() end, { desc = 'LiFFFe grep' })
	-- 		vim.keymap.set('n', "<leader>sz",
	-- 			function() fff.live_grep({ grep = { modes = { 'fuzzy', 'plain' } } }) end,
	-- 			{ desc = 'Live fffuzy grep' })
	-- 		vim.keymap.set('n', "<leader>sw", function() fff.live_grep_under_cursor() end,
	-- 			{ desc = 'Search current word / selection' })
	-- 	end
}
